language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          compiler: gcc
        - os: osx
          osx_image: xcode7.3
          compiler: gcc
        - os: osx
          osx_image: xcode7.3
          compiler: clang

before_install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            brew update
            brew install premake
        fi
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            sudo apt-get -qq update -y
            sudo apt-get install premake4 -y
        fi

before_script:
    - premake4 install

script:
    - premake4 gmake
    - cd build
    - make
    - cd Release
    - ./pontellaTest
    - cd ../../

after_script:
    - premake4 uninstall
